config/routes.rb
DemoApp::Application.routes.draw do
  resources :space_cats

end

app/models/space_cat.rb
class SpaceCat < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/space_cats_controller.rb
class SpaceCatsController < ApplicationController
  before_action :set_space_cat, only: [:show, :edit, :update, :destroy]

  # GET /space_cats
  # GET /space_cats.json
  def index
    @space_cats = SpaceCat.all
  end

  # GET /space_cats/1
  # GET /space_cats/1.json
  def show
  end

  # GET /space_cats/new
  def new
    @space_cat = SpaceCat.new
  end

  # GET /space_cats/1/edit
  def edit
  end

  # POST /space_cats
  # POST /space_cats.json
  def create
    @space_cat = SpaceCat.new(space_cat_params)

    respond_to do |format|
      if @space_cat.save
        format.html { redirect_to @space_cat, notice: 'Space cat was successfully created.' }
        format.json { render action: 'show', status: :created, location: @space_cat }
      else
        format.html { render action: 'new' }
        format.json { render json: @space_cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /space_cats/1
  # PATCH/PUT /space_cats/1.json
  def update
    respond_to do |format|
      if @space_cat.update(space_cat_params)
        format.html { redirect_to @space_cat, notice: 'Space cat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @space_cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /space_cats/1
  # DELETE /space_cats/1.json
  def destroy
    @space_cat.destroy
    respond_to do |format|
      format.html { redirect_to space_cats_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_space_cat
      @space_cat = SpaceCat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def space_cat_params
      params.require(:space_cat).permit(:name, :string, :planets_visited, :integer, :planet, :string)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/space_cats_helper.rb
module SpaceCatsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/space_cats/_form.html.erb
<%= form_for(@space_cat) do |f| %>
  <% if @space_cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@space_cat.errors.count, "error") %> prohibited this space_cat from being saved:</h2>

      <ul>
      <% @space_cat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :planets_visited %><br>
    <%= f.text_field :planets_visited %>
  </div>
  <div class="field">
    <%= f.label :integer %><br>
    <%= f.text_field :integer %>
  </div>
  <div class="field">
    <%= f.label :planet %><br>
    <%= f.text_field :planet %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/space_cats/edit.html.erb
<h1>Editing space_cat</h1>

<%= render 'form' %>

<%= link_to 'Show', @space_cat %> |
<%= link_to 'Back', space_cats_path %>

app/views/space_cats/index.html.erb
<h1>Listing space_cats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>String</th>
      <th>Planets visited</th>
      <th>Integer</th>
      <th>Planet</th>
      <th>String</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @space_cats.each do |space_cat| %>
      <tr>
        <td><%= space_cat.name %></td>
        <td><%= space_cat.string %></td>
        <td><%= space_cat.planets_visited %></td>
        <td><%= space_cat.integer %></td>
        <td><%= space_cat.planet %></td>
        <td><%= space_cat.string %></td>
        <td><%= link_to 'Show', space_cat %></td>
        <td><%= link_to 'Edit', edit_space_cat_path(space_cat) %></td>
        <td><%= link_to 'Destroy', space_cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Space cat', new_space_cat_path %>

app/views/space_cats/new.html.erb
<h1>New space_cat</h1>

<%= render 'form' %>

<%= link_to 'Back', space_cats_path %>

app/views/space_cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @space_cat.name %>
</p>

<p>
  <strong>String:</strong>
  <%= @space_cat.string %>
</p>

<p>
  <strong>Planets visited:</strong>
  <%= @space_cat.planets_visited %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @space_cat.integer %>
</p>

<p>
  <strong>Planet:</strong>
  <%= @space_cat.planet %>
</p>

<p>
  <strong>String:</strong>
  <%= @space_cat.string %>
</p>

<%= link_to 'Edit', edit_space_cat_path(@space_cat) %> |
<%= link_to 'Back', space_cats_path %>